/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package com.wdy.brobrosseur.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// COMMAND
	VIEW_COMMAND("VIEW_COMMAND"),	
	CREATE_COMMAND("CREATE_COMMAND"),
	UPDATE_COMMAND("UPDATE_COMMAND"),
	DELETE_COMMAND("DELETE_COMMAND"),
	// COURSIER
	VIEW_COURSIER("VIEW_COURSIER"),	
	CREATE_COURSIER("CREATE_COURSIER"),
	UPDATE_COURSIER("UPDATE_COURSIER"),
	DELETE_COURSIER("DELETE_COURSIER"),
	// COURSIER_MOYEN_DEPLACEMENT
	VIEW_COURSIER_MOYEN_DEPLACEMENT("VIEW_COURSIER_MOYEN_DEPLACEMENT"),	
	CREATE_COURSIER_MOYEN_DEPLACEMENT("CREATE_COURSIER_MOYEN_DEPLACEMENT"),
	UPDATE_COURSIER_MOYEN_DEPLACEMENT("UPDATE_COURSIER_MOYEN_DEPLACEMENT"),
	DELETE_COURSIER_MOYEN_DEPLACEMENT("DELETE_COURSIER_MOYEN_DEPLACEMENT"),
	// CUSTOMER
	VIEW_CUSTOMER("VIEW_CUSTOMER"),	
	CREATE_CUSTOMER("CREATE_CUSTOMER"),
	UPDATE_CUSTOMER("UPDATE_CUSTOMER"),
	DELETE_CUSTOMER("DELETE_CUSTOMER"),
	// EVALUATION_COMMAND
	VIEW_EVALUATION_COMMAND("VIEW_EVALUATION_COMMAND"),	
	CREATE_EVALUATION_COMMAND("CREATE_EVALUATION_COMMAND"),
	UPDATE_EVALUATION_COMMAND("UPDATE_EVALUATION_COMMAND"),
	DELETE_EVALUATION_COMMAND("DELETE_EVALUATION_COMMAND"),
	// EVALUATION_PRESTATION
	VIEW_EVALUATION_PRESTATION("VIEW_EVALUATION_PRESTATION"),	
	CREATE_EVALUATION_PRESTATION("CREATE_EVALUATION_PRESTATION"),
	UPDATE_EVALUATION_PRESTATION("UPDATE_EVALUATION_PRESTATION"),
	DELETE_EVALUATION_PRESTATION("DELETE_EVALUATION_PRESTATION"),
	// EVALUTATION_PROJET
	VIEW_EVALUTATION_PROJET("VIEW_EVALUTATION_PROJET"),	
	CREATE_EVALUTATION_PROJET("CREATE_EVALUTATION_PROJET"),
	UPDATE_EVALUTATION_PROJET("UPDATE_EVALUTATION_PROJET"),
	DELETE_EVALUTATION_PROJET("DELETE_EVALUTATION_PROJET"),
	// IMAGES_PRESTATION
	VIEW_IMAGES_PRESTATION("VIEW_IMAGES_PRESTATION"),	
	CREATE_IMAGES_PRESTATION("CREATE_IMAGES_PRESTATION"),
	UPDATE_IMAGES_PRESTATION("UPDATE_IMAGES_PRESTATION"),
	DELETE_IMAGES_PRESTATION("DELETE_IMAGES_PRESTATION"),
	// MOYEN_DEPLACEMENT
	VIEW_MOYEN_DEPLACEMENT("VIEW_MOYEN_DEPLACEMENT"),	
	CREATE_MOYEN_DEPLACEMENT("CREATE_MOYEN_DEPLACEMENT"),
	UPDATE_MOYEN_DEPLACEMENT("UPDATE_MOYEN_DEPLACEMENT"),
	DELETE_MOYEN_DEPLACEMENT("DELETE_MOYEN_DEPLACEMENT"),
	// PRESTATION
	VIEW_PRESTATION("VIEW_PRESTATION"),	
	CREATE_PRESTATION("CREATE_PRESTATION"),
	UPDATE_PRESTATION("UPDATE_PRESTATION"),
	DELETE_PRESTATION("DELETE_PRESTATION"),
	// PROJET
	VIEW_PROJET("VIEW_PROJET"),	
	CREATE_PROJET("CREATE_PROJET"),
	UPDATE_PROJET("UPDATE_PROJET"),
	DELETE_PROJET("DELETE_PROJET"),
	// RECORD_IMAGE
	VIEW_RECORD_IMAGE("VIEW_RECORD_IMAGE"),	
	CREATE_RECORD_IMAGE("CREATE_RECORD_IMAGE"),
	UPDATE_RECORD_IMAGE("UPDATE_RECORD_IMAGE"),
	DELETE_RECORD_IMAGE("DELETE_RECORD_IMAGE"),
	// UTILISATEUR
	VIEW_UTILISATEUR("VIEW_UTILISATEUR"),	
	CREATE_UTILISATEUR("CREATE_UTILISATEUR"),
	UPDATE_UTILISATEUR("UPDATE_UTILISATEUR"),
	DELETE_UTILISATEUR("DELETE_UTILISATEUR"),
	// VENDEUR
	VIEW_VENDEUR("VIEW_VENDEUR"),	
	CREATE_VENDEUR("CREATE_VENDEUR"),
	UPDATE_VENDEUR("UPDATE_VENDEUR"),
	DELETE_VENDEUR("DELETE_VENDEUR"),
	// ZONE_LIVRAISON
	VIEW_ZONE_LIVRAISON("VIEW_ZONE_LIVRAISON"),	
	CREATE_ZONE_LIVRAISON("CREATE_ZONE_LIVRAISON"),
	UPDATE_ZONE_LIVRAISON("UPDATE_ZONE_LIVRAISON"),
	DELETE_ZONE_LIVRAISON("DELETE_ZONE_LIVRAISON");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
